version: "3.9"
services:
  api:
    build: .
    container_name: api-first
    volumes:
      - ./:/var/www/html/api-first
    environment:
      - TZ=America/Sao_Paulo
    # env_file:
    #   - ./api/.env.local  
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:80
  db:
    image: mariadb
    container_name: first-db
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
      - MYSQL_DATABASE=first
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  adminer:
    image: adminer
    depends_on:
      - db
    restart: "no"
    ports:
      - 9504:8080
volumes:
  sql-data-zaffaricestto:
networks:
  default:
    name: first-network